#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --output=/volatile/halla/apex/mc/temp/slurm/%x.%j.out
#SBATCH --error=/volatile/halla/apex/mc/temp/slurm/%x.%j.err
#SBATCH --mem 4G

###########################################################################################
#
#   This script sets up the creation of 'Q1 tracks' via G4MC. 
#   The output root files are created in ${VOL_DIR}/tracks_Q1/.
#   The temp files are placed in their own directory in ${VOL_DIR}/temp/.
#
#   Required arguments:
#   $1 (first)  : Number of events to simulate
#
#   Suggested usage (Bash terminal):
#
#    > sbatch --job-name=apex_BH_Q1 --time=120 script_gen-Q1-tracks R 100000
#
#        submits 1 job, with a 90-minute deadline, for the RHRS, and 100k events.
#
#    > sbatch --job-name=apex_mc_Q1_R_V1 --time=120 script_gen-Q1-tracks L 200000 V1
#
#        1 job, 120 minutes, 200k events, LHRS, and V1 target. 
#
###########################################################################################

    
VOL_DIR="/volatile/halla/apex/mc"

PATH_G4MC="/work/halla/apex/disk1/sethhall/apex_mc_generator/g4mc"

#check if some of the necessary directories exist.

if [ ! -d "${PATH_G4MC}/slurm_infiles" ]; then
    echo "<script_gen-Q1-tracks>: ERROR: subdirectory 'slurm_infiles' does not exist in source directory '${PATH_G4MC}'. check variable 'PATH_G4MC'"
    exit 1;
fi

if [ ! -d "${VOL_DIR}/tracks_Q1" ]; then
    echo "<script_gen-Q1-tracks>: WARNING: directory '${VOL_DIR}/tracks_Q1' does not exist; are you sure your 'VOL_DIR' variable is correct?'"
    exit 1;
fi


target="production"

run_id=${SLURM_JOB_ID}

#check if we're within a slurm job; if not, then "${SLURM_JOB_ID}"=""
if [ ! "${SLURM_JOB_ID}" ]
then
    #We aren't in slurm mode. 
    run_id=0000
    echo "We are not in a slurm job..." 
else
    echo "Slurm job id: ${SLURM_JOB_ID}"
fi


echo "Run ID ${run_id}"


#check if the second argument exists, and if its an integer.
if [ ! "$1" ]; then echo "ERROR: Missing argument."; exit 1; fi

if [[ "$1" =~ ^-?[0-9]+$ ]]; then

    num_events=$1
    echo "Simulating ${num_events} events".
    
else
    echo "ERROR: Second argument '$2' must be an integer." 
    exit 1
fi

	
outfile_path="${VOL_DIR}/tracks_Q1/out_BH_${run_id}.root"

#check if the 'temp files' directory already exists. 
if [ -d "${VOL_DIR}/temp/job_${run_id}" ]
then 
    rm -rf "${VOL_DIR}/temp/job_${run_id}"
fi


#create a directory for the temporary files associated with this job
mkdir "${VOL_DIR}/temp/job_${run_id}"

cp -a "${PATH_G4MC}/slurm_infiles/." "${VOL_DIR}/temp/job_${run_id}/." 

cd "${VOL_DIR}/temp/job_${run_id}"

ln -s "${PATH_G4MC}/build/G4MC" "G4MC"


#prepare the 'run_settings.mac' file
# This first file, 'settings_base.txt' sets up generic run settings which are
# true for each run. 
if [ -f "settings_BetheHeitler_base.txt" ]
then
    cat "settings_BetheHeitler_base.txt" > run_settings.mac
    rm settings_BetheHeitler_base.txt
else
    echo "ERROR: 'settings_BetheHeitler_base.txt' does not exist"
    exit 1
fi

#tell G4MC where to put the output file
echo >> run_settings.mac
echo "/mydet/outfile ${outfile_path}" >> run_settings.mac

#create the 'beam.mac' file, which just tells G4MC how many events to run.
echo "/run/beamOn ${num_events}" > run.mac 

echo "<script_gen-A-prime>: Executing G4MC..." 

./G4MC -m 1 run_settings.mac run.mac

echo "<script_gen-A-prime>: Done with execution of G4MC." 

exit



