/run/verbose 2
/control/verbose 0
/tracking/verbose 0
/stepping/verbose 3
/mydet/verbose 3
/generator/verbose 3 
/tracking/particleOnly e-

/stepping/makeTXToutput false
/stepping/killAtQ1 true

# for the full simulation noSecondary 0, it only the primary track is needed to be simulated - then /tracking/noSecondary 1
/tracking/noSecondary 1
/tracking/thisTrackOnly 0
#see the same variable in HRSUsage.ini

# specify which arm to save data for - both, RHRS or LHRS
/global/arm_mode RHRS

# specify rel. path to save data to
/global/outfile_path test.root

# specify momentum generation / saving range
/global/momentum_low 1000 MeV
/global/momentum_high 1200 MeV

# specify acceptance on the face of the sieve (specified for RHRS, but applied to both arms)
/generator/sieve_x_low  -85 mm
/generator/sieve_x_high +85 mm
/generator/sieve_y_low  -80 mm
/generator/sieve_y_high +70 mm

# raster amplitude
/generator/vertical_raster_amplitude 2 mm
/generator/horizontal_raster_amplitude 2 mm

# which target to simulate: production, V1, V2, V3. 
/generator/target_mode V2

# expected number of events to be kept
/global/expected_n_events_kept 1000
