# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1
#
# specify whether sieve should be built
/detector/build_sieve true

#### Set some parameters of the particle generator ####
#
# mode of generation
/generator/mode trident_positron
#
# vertical raster amplitude
/generator/raster_amplitude 2 mm
#
# specify target
/generator/target V1

#
#
/generator/sampling_mode rejection


# specify minimum and maximum momentum to be written to file 
/global/min_momentum 1000 MeV
/global/max_momentum 2200 MeV

# specify which arm to use
/global/active_arm RHRS

# specify output file
/global/path_outfile test.root

 
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
