# Macro file for run on one of the sieves 
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 1

# Set verbosity 
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# specify whether sieve should be built
/detector/build_sieve false

#### Set some parameters of the particle generator ####
#
# mode of generation
/generator/mode trident_electron
#
/generator/sampling_mode rejection
#
# vertical raster amplitude
/generator/raster_amplitude 2 mm
#
# specify target
/generator/target V1


# specify minimum and maximum momentum to be written to file 
/global/min_momentum  999 MeV
/global/max_momentum 2201 MeV

# specify which arm to use
/global/active_arm LHRS

# specify output file
/global/path_outfile test_trident_electron.root


# Start the run 
/run/initialize
/run/beamOn 1000000


