# Macro file for run on one of the sieves 
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Set verbosity 
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Say whether sieve should be constructed
/detector/build_sieve true

# momenutm cuts
/global/min_momentum  999 MeV
/global/max_momentum 2201 MeV 

#### Set some parameters of the particle generator ####
# 
# vertical raster amplitude
/generator/raster_amplitude 2 mm
#
# sampling mode for the generator
/generator/sampling_mode rejection

