#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 20
#SBATCH --output=/volatile/halla/apex/mc/temp/slurm/%x.%j.out
#SBATCH --error=/volatile/halla/apex/mc/temp/slurm/%x.%j.err
#SBATCH --mem=8G 

source ~/.login


#check if we're within a slurm job; if not, then "${SLURM_JOB_ID}"=""
if [[ -z "${SLURM_JOB_ID}" ]]
then
    #We aren't in slurm mode. 
    run_id=0000
    n_cpus=$(nproc)
    if [[ $n_cpus -gt 16 ]]; then n_cpus=16; fi 
    echo "We are not in a slurm job. n_cpus=${n_cpus}, run_id=${run_id}"     
    
else
    run_id=${SLURM_JOB_ID}
    n_cpus=${SLURM_CPUS_PER_TASK}
    echo "Slurm job id: ${SLURM_JOB_ID}"

fi

arm=${1}
target=${2}
process=${3}
n_events=${4}

# Path to source directory 
SRC_DIR="${WORK_APEX}/apex_mc_generator/sieve_simulation" 

# path to scratch disk 
SCRATCH_DIR="/volatile/halla/apex/mc/temp/job_${run_id}"

# path to place to put files on the volatile disk
OUTPUT_DIR="/volatile/halla/apex/mc/tracks_sieve"

if [ -d "${SCRATCH_DIR}" ]; then
    echo "<${0}>: Overwriting directory '${SCRATCH_DIR}'" 
    rm -rf ${SCRATCH_DIR}/*
else
    echo "<${0}>: Creating directory '${SCRATCH_DIR}'" 
    mkdir ${SCRATCH_DIR}
fi 
    
cd ${SCRATCH_DIR}
cp -r ${SRC_DIR}/* .

cat slurm_run.mac > my_run.mac

path_outfile="${OUTPUT_DIR}/out_sieve_${arm}_${target}_${process}_${run_id}.root"

echo "" >> my_run.mac
echo "# set number of worker threads" >> my_run.mac
echo "/run/numberOfThreads ${n_cpus}" >> my_run.mac

echo "" >> my_run.mac
echo "# Set output file" >> my_run.mac
echo "/global/path_outfile ${path_outfile}" >> my_run.mac

echo "" >> my_run.mac
echo "# Pick which arm to use" >> my_run.mac
echo "/global/active_arm ${arm}" >> my_run.mac

echo "" >> my_run.mac
echo "# Pick which target to simulate" >> my_run.mac
echo "/generator/target ${target}" >> my_run.mac

echo "" >> my_run.mac
echo "# Pick which process to simulate" >> my_run.mac
echo "/generator/mode ${process}" >> my_run.mac

echo "" >> my_run.mac
echo "# Start the run" >> my_run.mac
echo "/run/initialize" >> my_run.mac
echo "/run/beamOn ${n_events}" >> my_run.mac 

echo "<${0}>: Executing G4 application" 
time ./exampleB1 my_run.mac
echo "<${0}>: done."

hadd -k -j=${n_cpus} "${path_outfile}" "${OUTPUT_DIR}/out_sieve_${arm}_${target}_${process}_${run_id}_"* && rm "${OUTPUT_DIR}/out_sieve_${arm}_${target}_${process}_${run_id}_"*





